feat(save): Just saving my work for a quick moment
Signed-off-by: Kris Nova <kris@nivenly.com>

diff --git a/bin/build-falco b/bin/build-falco
--- a/bin/build-falco
+++ b/bin/build-falco
@@ -12,29 +12,27 @@
 # specific language governing permissions and limitations under the License.
 #
 #
-# The main logic for Nóva's bash hackery for her Falco + Fargate demos
-
-
-# The port that we can "hack" into our fargate task with
+# Common directories for the project
 #
-# Use nc -nv <ip> <port> to access a remote shell
-#
+FALCO_TRACE_BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+FALCO_DIR=${FALCO_TRACE_BIN_DIR}/../falco
+SYSDIG_DIR=${FALCO_TRACE_BIN_DIR}/../sysdig
+PDIG_DIR=${FALCO_TRACE_BIN_DIR}/../pdig
 
-CLEAN=${CLEAN:-false}
-
-cd falco/build
-FALCO_BUILD=$(pwd)
-
-if [[ "$CLEAN" ]]; then
-    echo "Cleaning falco/build"
-    rm -rf *
-fi
+CORES=48
 
 
+mkdir -p $FALCO_DIR/build
+cd $FALCO_DIR/build
+make clean
 cmake ../ \
       -DBUILD_BPF=OFF \
       -DBUILD_WARNINGS_AS_ERRORS="OFF" \
       -DCMAKE_BUILD_TYPE="Release" \
       -DCMAKE_INSTALL_PREFIX="/usr" \
-      -DFALCO_ETC_DIR="/etc/falco" \
-      -DUSE_BUNDLED_DEPS=ON
+      -DFALCO_ETC_DIR="/etc/falco"
+
+make all -j${CORES}
+if [ $? -ne 0 ]; then
+ echo "FAILURE: Unable to compile Falco"
+fi
diff --git a/bin/pdig b/bin/pdig
--- a/bin/pdig
+++ b/bin/pdig
@@ -1,6 +1,46 @@
 #!/bin/bash
-EXPOSE_PORT=443
+#
+# Copyright (C) 2019 The Falco Authors.
+#
+# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
+# the License. You may obtain a copy of the License at
+#
+# http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
+# specific language governing permissions and limitations under the License.
+#
+#
+# Common directories for the project
+#
+FALCO_TRACE_BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+FALCO_DIR=${FALCO_TRACE_BIN_DIR}/../falco
+SYSDIG_DIR=${FALCO_TRACE_BIN_DIR}/../sysdig
+PDIG_DIR=${FALCO_TRACE_BIN_DIR}/../pdig
+
+#
+# #The port that we can "hack" into our fargate task with
+#
+# Use nc -nv <ip> <port> to access a remote shell
+#
+NCAT_EXPOSE_PORT=${NCAT_EXPOSE_PORT:-443}
+
+
+function exec_pdig() {
+  //
+}
+
+function exec_falco() {
+
+}
+
+exit 1
 while :
 do
    ncat -nvlp ${EXPOSE_PORT} -e /bin/bash
+   if [ $? -ne 0 ]; then
+      printf "Error with ncat. Sleeping...\n"
+      sleep 3
+   fi
 done
