feat(init): Working demo
Signed-off-by: Kris Nova <kris@nivenly.com>

diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -19,40 +19,18 @@ FALCO_DIR=${FALCO_TRACE_BIN_DIR}/../falco
 SYSDIG_DIR=${FALCO_TRACE_BIN_DIR}/../sysdig
 PDIG_DIR=${FALCO_TRACE_BIN_DIR}/../pdig
 
-CORES=48
-
 #
-# Install Packages for Falco
+# #The port that we can "hack" into our fargate task with
 #
-apt-get update
-apt-get install -y --no-install-recommends \
-	ncat \
-	make \
-	cmake \
-	gcc \
-	clang \
-	apt-utils \
-	jq
+# Use nc -nv <ip> <port> to access a remote shell
+#
+PORT=${PORT:-443}
 
-jq
-
-exit 1
-
-# Reset the cache and clean every stinkin time
-rm -rf $FALCO_DIR/build
-mkdir -p $FALCO_DIR/build
-cd $FALCO_DIR/build
-cmake ../ \
-      -DBUILD_BPF=OFF \
-      -DBUILD_WARNINGS_AS_ERRORS="OFF" \
-      -DCMAKE_BUILD_TYPE="Release" \
-      -DCMAKE_INSTALL_PREFIX="/usr" \
-      -DFALCO_ETC_DIR="/etc/falco"
-
-make all -j${CORES}
-if [ $? -ne 0 ]; then
- echo "FAILURE: Unable to compile Falco"
-fi
-make clean
-
-# TODO Logic for installing falco in container
+while :
+do
+   ncat -nvlp ${PORT} -e /bin/bash
+   if [ $? -ne 0 ]; then
+      printf "Error with ncat. Sleeping...\n"
+      sleep 3
+   fi
+done
